#!/usr/bin/lua
local lfs = require"lfs"

local compose = [[
  version: '3.9'

  services:
    application:
      image: "rousbound/cgilua:latest"
      tty: true
      container_name: "$$PROJECT_NAME$$"
      hostname: "$$PROJECT_NAME$$"
      volumes:
        - "$$CWD$$/src:/home/app/src"
        - "$$CWD$$/logs:/home/app/logs"
        - "$$CWD$$/backup:/home/app/backup"
        - "$$CWD$$/luarocks:/home/app/.luarocks"
      ports: 
        - "8888:80"
        - "2222:22"
    db:
      image: "postgres-cgilua:14"
      restart: always
      container_name: "$$PROJECT_NAME$$-db"
]]

local example = [[
#!/usr/bin/env cgilua.cgi

cgilua.put("Hello Lua!")
]]

local base = [[
#!/usr/bin/env cgilua.cgi
  
]]

local cgilua_bin = [[
#!/bin/sh

LUAROCKS_SYSCONFDIR='/etc/luarocks' exec '/usr/bin/lua5.3' -e 'package.path="/home/app/.luarocks/share/lua/5.3/?.lua;/home/app/.luarocks/share/lua/5.3/?/init.lua;"..package.path;package.cpath="/home/app/.luarocks/lib/lua/5.3/?.so;"..package.cpath;local k,l,_=pcall(require,"luarocks.loader") _=k and l.add_context("cgilua","6.0.2-0")' '/home/app/.luarocks/lib/luarocks/rocks-5.3/cgilua/6.0.2-0/bin/cgilua.cgi' "$@"  
]]

local cgilua_config = [[
  local app_lib_dir = {
    ["modules"] = "/home/app/src/modules"
  }

  local cgilua = require"cgilua"
  cgilua.addopenfunction (function ()
  	cgilua.script_vdir = cgilua.splitonlast(cgilua.urlpath):gsub("%/+", "/")
  	local package = package
  	local app = app_lib_dir[cgilua.script_vdir]
  	if app then
  		package.path = app.."/?.lua;"..app.."/?/init.lua;"..package.path
  	end
  end)
]]

local function subs (s, t)
	return (s:gsub ("%$%$([_%w]+)%$%$", t))
end

local function install(path, rock, extra)
  local cmd = (path and ("cd ".. path .. " && ") or "") .. "luarocks install " .. rock .." --tree=luarocks --lua-version=5.3" .. " " .. (extra and table.concat(extra, " ") or "")
  local fh = assert(io.popen(cmd))
  print(fh:read("*a"))
end

local function exec(cmd)
  print(cmd)
  os.execute(cmd)
end

local base_rocks = {
  "wsapi",
  "cgilua",
  "dado",
  -- {"luasql-postgres", {"PGSQL_INCDIR=/usr/include/postgresql"}}
}

local cmds = {}
local order = {}


local function command(cmd, f)
  cmds[cmd] = f
  table.insert(order, cmd)

end


local function write(file_name, content)
    local fh, err  = assert(io.open(file_name, "w"))
    fh:write(content)
end
command("new", function(args)
    local prj = args[2]
    local prj_compose = subs(compose, {
      PROJECT_NAME = prj,
      CWD = lfs.currentdir() .. "/" .. prj
    })
    local paths = {
      "/logs",
      "/src",
      "/src/migrations",
      "/src/controller",
      "/src/shell",
      "/src/modules",
      "/.luarocks",
      "/backup"
    }
    lfs.mkdir(prj)
    for _, path in ipairs(paths) do
      lfs.mkdir(prj .. path)
    end
    write(prj.."/src/controller/main.lua", example)
    exec("chmod a+x " .. prj .. "/src/controller/main.lua")
    write(prj .. "/" .. "docker-compose.yml", prj_compose)
    for _, v in ipairs(base_rocks) do
      local rock, extra
      if type(v) == "table" then
        rock, extra = table.unpack(v)
      else
        rock = v
      end
      install(prj, rock, extra)
    end
    write(prj .. "/luarocks/bin/cgilua.cgi", cgilua_bin)
    write(prj .. "/src/controller/config.lua", cgilua_config)
end)

command("shell", function(args)
  exec("ssh -p 2222 app@localhost")
end)

command("up",
function(args)
  exec("sudo docker compose up -d")
end)

command("install", function(args)
  install(nil, args[2])
end)

command("add", function(args)
  write("src/controller/"..args[2], base)
  exec("chmod a+x src/controller/"..args[2])
end
)

local cmd = cmds[arg[1]]

if cmd then
  cmd(arg)
else
  print("Invalid argument, received: " .. table.concat(arg," ") .. "\n"..
    "Expected: one of the following: \n  " .. table.concat(order, "\n  ")
  )
end

